# Generated by Django 2.1.2 on 2018-10-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181030_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry_pi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
