# Generated by Django 2.1.2 on 2018-12-14 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181214_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry_pi',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 14, 9, 8, 34, 10780)),
        ),
    ]
