# Generated by Django 2.1.2 on 2018-12-26 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181214_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raspberry_pi',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 26, 13, 30, 48, 124870)),
        ),
    ]
